export const HarvardStyle: Record<string, object> =  {
    profile: {
      container: { marginBottom: 16 },
      name: { fontSize: 20, fontWeight: 'bold', textAlign: 'center' },
      contactRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', marginTop: 4 },
      contactItem: { fontSize: 10, marginRight: 6 },
      summary: { fontSize: 10, marginTop: 6, textAlign: 'justify' },
    },
    education: {
      container: { marginBottom: 14 },
      title: { fontSize: 13, fontWeight: 'bold' },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 11 },
      separator: { fontSize: 11 },
      subtitle: { fontSize: 12 },
      location: { fontSize: 11 },
      description: { fontSize: 11, margin: 0, padding: 0, lineHeight: 1 },
      gpa: { fontSize: 11 },
    },
    experience: {
      container: { marginBottom: 14 },
      title: { fontSize: 13, fontWeight: 'bold' },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 11 },
      separator: { fontSize: 11 },
      subtitle: { fontSize: 12 },
      location: { fontSize: 11 },
      description: { fontSize: 11, margin: 0, padding: 0, lineHeight: 1 },
    },
    project: {
      container: { marginBottom: 12 },
      title: { fontSize: 12, fontWeight: 'bold' },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 11 },
      separator: { fontSize: 11 },
      description: { fontSize: 11, margin: 0, padding: 0, lineHeight: 1 },
    },
    skills: {
      container: { marginBottom: 8 },
      row: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
      skillName: { fontSize: 12, marginRight: 6 },
      skillRating: { fontSize: 16, fontWeight: 'bold' },
      skillDescription: { fontSize: 11, marginTop: 2 },
    },
    custom: {
      container: { marginBottom: 12 },
      title: { fontSize: 12, fontWeight: 'bold' },
      description: { fontSize: 11, margin: 0, padding: 0, lineHeight: 1 },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 11 },
      subtitle: { fontSize: 12 },
      location: { fontSize: 11 },
    },
}