export const MITStyle: Record<string, object> = {
    profile: {
      container: { marginBottom: 16 },
      name: { fontSize: 18, fontWeight: 'bold', textAlign: 'center' },
      contactRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', marginTop: 4 },
      contactItem: { fontSize: 10, marginRight: 8 },
      summary: { fontSize: 10, marginTop: 8, textAlign: 'justify' },
    },
    education: {
      container: { marginBottom: 12 },
      titleRow: { display:'flex', flexDirection:'row', justifyContent:'space-between'},
      title: { fontSize: 12, fontWeight: 'bold' },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 10 },
      separator: { fontSize: 10 },
      subTitleRow: { display:'flex', flexDirection:'row', justifyContent:'space-between'},
      subtitle: { fontSize: 11 },
      location: { fontSize: 10 },
      description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1 },
      gpa: { fontSize: 10 },
    },
    experience: {
      container: { marginBottom: 12 },
      titleRow: { display:'flex', flexDirection:'row', justifyContent:'space-between'},
      title: { fontSize: 12, fontWeight: 'bold'},
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 10 },
      separator: { fontSize: 10 },
      subTitleRow: { display:'flex', flexDirection:'row', justifyContent:'space-between'},
      subtitle: { fontSize: 11 },
      location: { fontSize: 10 },
      description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1 },
    },
    project: {
      container: { marginBottom: 12 },
      titleRow: { display:'flex', flexDirection:'row', justifyContent:'space-between'},
      title: { fontSize: 12, fontWeight: 'bold' },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 10 },
      separator: { fontSize: 10 },
      subtitle: { fontSize: 11 },
      description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1 },
    },
    skills: {
      container: { marginBottom: 8 },
      row: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
      name: { fontSize: 11, marginRight: 8 },
      rating: { fontSize: 16, fontWeight: 'bold' },
      description: { fontSize: 10, marginTop: 2 },
    },
    custom: {
      container: { marginBottom: 12 },
      title: { fontSize: 12, fontWeight: 'bold' },
      description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1 },
      dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
      date: { fontSize: 10 },
      subtitle: { fontSize: 11 },
      location: { fontSize: 10 },
    },
}