export const HarvardStyle: Record<string, object> = {
  profile: {
    container: { marginBottom: 18 },
    name: { fontSize: 20, fontWeight: 'bold', textAlign: 'center', color: 'black', letterSpacing: 0.5 },
    contactRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', marginTop: 6, alignItems:"center" },
    contactItem: { fontSize: 10, marginRight: 10, color: 'black' },
    contactUrl: { fontSize: 10, marginRight: 8, color: 'black', textDecoration: 'none' },
    contactIcon: {fontSize: 10, marginRight: 5, color: 'black'},
    summary: { fontSize: 11, marginTop: 10, textAlign: 'justify', color: 'black', lineHeight: 1.4 },
  },
  education: {
    container: { marginBottom: 14 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
    title: { fontSize: 13, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subTitleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    subtitle: { fontSize: 11, fontStyle: 'italic', color: 'black' },
    location: { fontSize: 10, color: 'black' },
    description: { fontSize: 10, marginTop: 2, lineHeight: 1.3, color: 'black' },
    gpa: { fontSize: 10, color: 'black' },
  },
  experience: {
    container: { marginBottom: 14 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
    title: { fontSize: 13, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subTitleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    subtitle: { fontSize: 11, fontStyle: 'italic', color: 'black' },
    location: { fontSize: 10, color: 'black' },
    description: { fontSize: 10, marginTop: 2, lineHeight: 1.3, color: 'black' },
  },
  project: {
    container: { marginBottom: 14 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
    title: { fontSize: 13, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subtitle: { fontSize: 11, fontStyle: 'italic', color: 'black' },
    description: { fontSize: 10, marginTop: 2, lineHeight: 1.3, color: 'black' },
  },
  skills: {
    container: { marginBottom: 10 },
    row: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    name: { fontSize: 11, marginRight: 8, color: 'black' },
    rating: { fontSize: 15, fontWeight: 'bold', color: 'black' },
    description: { fontSize: 10, marginTop: 2, color: 'black' },
  },
  custom: {
    container: { marginBottom: 14 },
    title: { fontSize: 13, fontWeight: 'bold', color: 'black' },
    subtitle: { fontSize: 11, fontStyle: 'italic', color: 'black' },
    description: { fontSize: 10, marginTop: 2, lineHeight: 1.3, color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    location: { fontSize: 10, color: 'black' },
  },
};
