export const MITStyle: Record<string, object> = {
  profile: {
    container: { marginBottom: 16 },
    name: { fontSize: 18, fontWeight: 'bold', textAlign: 'center', color: 'black' },
    contactRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', marginTop: 4 },
    contactItem: { fontSize: 10, marginRight: 8, color: 'black' },
    summary: { fontSize: 10, marginTop: 8, textAlign: 'justify', color: 'black' },
  },
  education: {
    container: { marginBottom: 12 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    title: { fontSize: 12, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subTitleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    subtitle: { fontSize: 11, color: 'black' },
    location: { fontSize: 10, color: 'black' },
    description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1, color: 'black' },
    gpa: { fontSize: 10, color: 'black' },
  },
  experience: {
    container: { marginBottom: 12 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    title: { fontSize: 12, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subTitleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    subtitle: { fontSize: 11, color: 'black' },
    location: { fontSize: 10, color: 'black' },
    description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1, color: 'black' },
  },
  project: {
    container: { marginBottom: 12 },
    titleRow: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
    title: { fontSize: 12, fontWeight: 'bold', color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    separator: { fontSize: 10, color: 'black' },
    subtitle: { fontSize: 11, color: 'black' },
    description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1, color: 'black' },
  },
  skills: {
    container: { marginBottom: 8 },
    row: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    name: { fontSize: 11, marginRight: 8, color: 'black' },
    rating: { fontSize: 16, fontWeight: 'bold', color: 'black' },
    description: { fontSize: 10, marginTop: 2, color: 'black' },
  },
  custom: {
    container: { marginBottom: 12 },
    title: { fontSize: 12, fontWeight: 'bold', color: 'black' },
    description: { fontSize: 10, margin: 0, padding: 0, lineHeight: 1, color: 'black' },
    dateRow: { flexDirection: 'row', justifyContent: 'space-between' },
    date: { fontSize: 10, color: 'black' },
    subtitle: { fontSize: 11, color: 'black' },
    location: { fontSize: 10, color: 'black' },
  },
};
